<?php

namespace UserBundle\Repository;

use ZND\SIM\ApiBundle\Repository\ApiRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends ApiRepository
{

}
